# Generated by Django 4.2.29 on 2026-03-11 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedpaper',
            name='ai_prompt_used',
        ),
        migrations.AddField(
            model_name='generatedpaper',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_papers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AssignedPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_assignments', to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='papers.generatedpaper')),
                ('students', models.ManyToManyField(related_name='assigned_papers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
