# Generated by Django 4.2.29 on 2026-03-22 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0001_initial'),
        ('papers', '0002_remove_generatedpaper_ai_prompt_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousYearPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='old_papers/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_papers', to='exams.examtype')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_old_papers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
