# Generated by Django 4.2.29 on 2026-03-24 17:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('papers', '0003_previousyearpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedpaper',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='exams.subject'),
        ),
        migrations.AlterField(
            model_name='previousyearpaper',
            name='file',
            field=models.FileField(upload_to='old_papers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
