# Generated by Django 4.2.29 on 2026-03-21 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_centres', '0001_initial'),
        ('users', '0003_registrationrequest_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coaching_centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='coaching_centres.coachingcentre'),
        ),
    ]
