# Generated by Django 4.2.29 on 2026-03-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_coaching_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='centre_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='centre_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor'), ('coaching_centre', 'Coaching Centre')], default='student', max_length=20),
        ),
    ]
