# Generated by Django 4.2.29 on 2026-03-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_studentinstructorassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='degree_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='intermediate_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='tenth_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='degree_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='intermediate_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tenth_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
