# Generated by Django 4.2.29 on 2026-03-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_registrationrequest_degree_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationrequest',
            name='parent_details',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parent_details',
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='parent_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
