# Generated by Django 4.2.29 on 2026-03-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
